---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "def-surface-svc"
  labels:
    app: def-surface
    release: v1
    env: dev
  annotations:
    cloud.google.com/app-protocols: '{"def-gui-https":"HTTPS","def-admin-https":"HTTPS"}'
spec:
  type: "NodePort"
  ports:
    - name: "def-gui-https"
      port: 443
      targetPort: 443
      protocol: TCP
    - name: "def-admin-https"
      port: 10101
      targetPort: 10101
      protocol: TCP	  
  selector:
    app: "def"
    release: "v1"
    component: "server"
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: search-dahu-certificate
spec:
  domains:
    - dahu.co.uk
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: search-dahu-certificate-temp
spec:
  domains:
    - 130.211.33.224.xip.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dahu-ingress
  annotations:
    ingress.kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: dahu-aodocs-test-ip
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    networking.gke.io/managed-certificates: search-dahu-certificate-temp
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: def-surface-svc
              servicePort: 443
          - path: /admin/*
            backend:
              serviceName: def-surface-svc
              servicePort: 10101
---
apiVersion: v1
kind: Pod
metadata:
  name: def
  labels:
    app: def
    release: v1
    env: dev
    component: server
spec:
  volumes:
    - name: def-disk
      gcePersistentDisk:
        pdName: def
        fsType: ext4
    - name: service-account
      configMap:
        name: service
  nodeSelector:
    servicetype: def
  containers:
    - name: def
      image: gcr.io/dahu-search/def:v1.1.3
      imagePullPolicy: Always
      ports:
        - containerPort: 443
          name: def-gui-https
          protocol: TCP
        - containerPort: 10101
          name: def-admin-https
          protocol: TCP		  		  
        - containerPort: 80
          name: def-gui-http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /healthcheck/ping
          port: 80
        initialDelaySeconds: 240
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /healthcheck/ping
          port: 80
        initialDelaySeconds: 240
        periodSeconds: 10
      volumeMounts:
        - name: def-disk
          mountPath: /data
        - name: service-account
          mountPath: /tmp/service.json
      env:
        - name: GIT_APP_NAME
          value: aodocs-demo
        - name: AODOCS_DOMAIN_ADMIN
          value: vince@dahu.co.uk
        - name: APPNAME
          value: "Dahu Search"
        - name: GIT_REPO
          value: dahu.codebasehq.com
        - name: GIT_REPO_URL
          value: "https://dahu.codebasehq.com/def35-client-projects/aodocs-demo.git"
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: dahu.git
              key: gituser
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dahu.git
              key: gitpwd
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: service.json
